// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: proto/detu.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "detu";

/** Đệ tử (bản rút gọn) */
export interface DeTu {
  id: number;
  userId: number;
  sucManh: number;
}

/** --- SAVE GAME DE TU --- */
export interface SaveGameDeTuRequest {
  userId: number;
  sucManh: number;
}

export interface SaveGameDeTuResponse {
  message: string;
}

/** --- CREATE DE TU --- */
export interface CreateDeTuRequest {
  userId: number;
  sucManh: number;
}

export interface CreateDeTuResponse {
  message: string;
}

/** --- GET DE TU --- */
export interface GetDeTuRequest {
  userId: number;
}

export interface DeTuResponse {
  detu: DeTu | undefined;
}

export const DETU_PACKAGE_NAME = "detu";

/** ===== SERVICE DEFINITION ===== */

export interface DeTuServiceClient {
  saveGameDeTu(request: SaveGameDeTuRequest, metadata?: Metadata): Observable<SaveGameDeTuResponse>;

  createDeTu(request: CreateDeTuRequest, metadata?: Metadata): Observable<CreateDeTuResponse>;

  getDeTuByUserId(request: GetDeTuRequest, metadata?: Metadata): Observable<DeTuResponse>;
}

/** ===== SERVICE DEFINITION ===== */

export interface DeTuServiceController {
  saveGameDeTu(request: SaveGameDeTuRequest, metadata?: Metadata): Observable<SaveGameDeTuResponse>;

  createDeTu(request: CreateDeTuRequest, metadata?: Metadata): Observable<CreateDeTuResponse>;

  getDeTuByUserId(request: GetDeTuRequest, metadata?: Metadata): Observable<DeTuResponse>;
}

export function DeTuServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["saveGameDeTu", "createDeTu", "getDeTuByUserId"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("DeTuService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("DeTuService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const DE_TU_SERVICE_NAME = "DeTuService";
